#!/usr/bin/env python3
"""Contract-text regression tests for MOA-471 items 2 (prose half), 3, 4, 5.

Stdlib-only: reads the three contract markdown files as text and asserts directly on
their content. No markdown parser on purpose -- these contracts are prose read by a
one-shot model, not a schema; the assertions pin the exact sentences/phrases the spec
requires, and catch a future edit silently reintroducing an obsolete claim
(`--prompt-file`, a blanket full-read instruction, a manual `git worktree`/`checkout -b`
step) or dropping a required one.
"""
import pathlib
import re

CONTRACTS = pathlib.Path(__file__).resolve().parent.parent / "workflow" / "contracts"


def _read(name):
    return (CONTRACTS / name).read_text(encoding="utf-8")


# --- builder-contract.md (item 2, prose half) --------------------------------------

def test_builder_contract_no_blanket_full_read():
    builder = _read("builder-contract.md")
    assert "Read the entire handoff package and every referenced document" not in builder
    assert "consultation material" in builder
    assert "#<heading>" in builder
    assert "next heading of the same or higher level" in builder
    # paths.plan is mandatory and whole -- only paths.spec is fragment-scoped
    assert "never optional, never fragment-scoped" in builder


def test_builder_contract_worktree_setup_step():
    """A fresh worktree has no deps/env (arc build e1665ddb8ef6, 2026-09-11: vitest and
    eslint 'not found', exit 127); the contract must make setup explicit per project."""
    builder = _read("builder-contract.md")
    assert "Make the worktree runnable before the first task" in builder
    assert "`AGENTS.md` names" in builder
    assert "`result: blocked` naming the failed step" in builder
    # the step lives right after the AGENTS.md rule it depends on
    assert builder.index("Follow the target project's `AGENTS.md`") < builder.index(
        "Make the worktree runnable before the first task")


# --- reviewer-contract.md (item 2 fragment wording + item 5 prior-review input) ----

def test_reviewer_contract_fragment_narrows_not_widens():
    reviewer = _read("reviewer-contract.md")
    assert "next heading of the same or higher level" in reviewer
    assert "never widens the read scope" in reviewer
    # "Read nothing else" stays in force -- the sealed-envelope language is not removed
    assert "nothing else" in reviewer


def test_reviewer_contract_document_review_checks_its_own_citations():
    """A document review was a closed reading, so a spec's `file:line` claims went
    unchecked: the MOA-470 spec's `cmd_result` ordering claim survived two rounds and
    was only caught at plan stage. The grant must stay narrow and must never push code
    into specs."""
    reviewer = _read("reviewer-contract.md")
    assert "`path:line` citations are readable evidence" in reviewer
    assert "covers the cited files\n  and nothing else" in reviewer
    assert "never demand that a spec or" in reviewer
    # the closed-reading frame survives: the document is still the object under review
    assert "sole object under review" in reviewer


def test_reviewer_contract_prior_review_input():
    reviewer = _read("reviewer-contract.md")
    assert "Correction review of" in reviewer
    assert "paths.prior-review" in reviewer
    assert "additive to the sealed" in reviewer
    assert "handoff:paths.prior-review" in reviewer
    assert "never the sealed builder report" in reviewer


# --- orchestrator-handoff.md (items 3 and 4) ----------------------------------------

def test_orchestrator_handoff_no_prompt_file_claim():
    handoff = _read("orchestrator-handoff.md")
    assert "--prompt-file" not in handoff


def test_orchestrator_handoff_no_manual_git_instructions():
    handoff = _read("orchestrator-handoff.md")
    assert "git checkout -b" not in handoff
    assert "git worktree add" not in handoff
    assert "git rev-parse --verify" not in handoff


def test_orchestrator_handoff_packages_labeled_generated():
    handoff = _read("orchestrator-handoff.md")
    assert "generated by jaxflow" in handoff.lower()
    assert "not authored here" in handoff


def test_orchestrator_handoff_plan_authoring_must_should():
    handoff = _read("orchestrator-handoff.md")
    assert "## PLAN AUTHORING" in handoff
    assert "MUST carry" in handoff
    assert "SHOULD carry" in handoff
    assert "MUST resolve" in handoff


def test_orchestrator_handoff_quiet_reporter_convention():
    handoff = _read("orchestrator-handoff.md")
    assert "reporter=dot" in handoff
    assert "pytest -q" in handoff
    assert "exit status" in handoff
    assert "| tail" not in handoff


def test_orchestrator_handoff_reviewer_package_prior_review():
    handoff = _read("orchestrator-handoff.md")
    assert "prior-review" in handoff
    assert "sealed by design" in handoff
    # the layout's leading correction-round line, matching reviewer-contract.md's marker
    assert "Correction review of" in handoff
    assert "review --diff --since" in handoff


def test_orchestrator_handoff_lead_runtime_addendum_unchanged():
    handoff = _read("orchestrator-handoff.md")
    assert "## LEAD RUNTIME ADDENDUM" in handoff
    assert "decision capsule of at most 300 characters" in handoff


def _section(text, heading):
    """Slices from an exact `##`-heading line through the line before the next `##`
    heading, or EOF -- so an assertion scoped to ONE contract section never sees
    another section's own example block or prose (MOA-472 F2)."""
    lines = text.split("\n")
    start = next(i for i, line in enumerate(lines) if line == heading)
    end = start + 1
    while end < len(lines) and not lines[end].startswith("## "):
        end += 1
    return "\n".join(lines[start:end])


def test_orchestrator_handoff_no_goal_task_acceptance_fields():
    handoff = _read("orchestrator-handoff.md")
    assert "goal:" not in handoff
    assert "tasks:" not in handoff
    assert "acceptance:" not in handoff


def test_builder_contract_no_final_tests_txt_obligation():
    builder = _read("builder-contract.md")
    assert "Success without this evidence is a contract violation" not in builder
    assert "TDD loop" in builder


def test_status_report_contract_no_frontmatter_block_required():
    report = _section(_read("status-report-contract.md"), "## REPORT FILE (report.md)")
    assert "```markdown\n---\n" not in report
    assert "Stage 2" in report
    assert "No `---` block is required" in report


def test_status_report_contract_has_no_role_example():
    # F2: the proposed Stage 2 prose legitimately says "`result:` for a builder" and
    # "`verdict:` for a reviewer" -- naming a label in prose is allowed. What must be
    # gone is the FENCED example block that showed both roles' keys side by side (now
    # split into builder-contract.md/reviewer-contract.md, Steps 4-5 below). Scoped to
    # the REPORT FILE section so the STATUS FILE section's own unrelated fence never
    # makes this pass for the wrong reason.
    report = _section(_read("status-report-contract.md"), "## REPORT FILE (report.md)")
    assert "```markdown\n---\n" not in report


def test_builder_contract_report_example_has_result_never_verdict():
    builder = _read("builder-contract.md")
    assert "## REPORT FRONTMATTER EXAMPLE" in builder
    assert "result: success | failure | blocked" in builder
    assert "verdict:" not in builder


def test_reviewer_contract_report_example_has_verdict_never_result():
    reviewer = _read("reviewer-contract.md")
    assert "## REPORT FRONTMATTER EXAMPLE" in reviewer
    assert "verdict: approve | approve-with-changes | reject" in reviewer
    assert "result:" not in reviewer


def test_merge_contract_approval_is_agreement_to_a_question():
    merge = _read("merge-contract.md")
    assert "Any clear agreement to that question" in merge
    assert "never has to repeat identifiers" in merge
    assert "full 40-character head SHA" not in merge


def test_merge_contract_fast_forward_exception():
    merge = _read("merge-contract.md")
    assert "strict descendant" in merge
    assert "fast-forward" in merge
    assert "EQUAL tip is never treated as a fast-forward" in merge


def test_merge_contract_pins_the_canonical_merge_question():
    merge = _read("merge-contract.md")
    assert "Posso mergear `<branch>` em `<destination>`?" in merge
    assert "May I merge `<branch>` into `<destination>`?" in merge
    assert "Approve merge" in merge


TEMPLATE = CONTRACTS.parent / "templates" / "AGENTS-template.md"
_PRESET_HEADING = re.compile(r"^\*\*Preset: `([a-z-]+)`\*\* — (.+)$", re.M)


def test_agents_template_has_the_five_presets_with_market_names_and_protection():
    text = TEMPLATE.read_text(encoding="utf-8")
    headings = _PRESET_HEADING.findall(text)
    assert [name for name, _ in headings] == [
        "single-branch", "single-branch-pr", "dual-branch", "dual-branch-pr", "bubble-buildprint"]
    market = {
        "single-branch": "trunk-based development",
        "single-branch-pr": "GitHub Flow",
        "dual-branch": "environment branches",
        "dual-branch-pr": "GitLab Flow with PRs",
        "bubble-buildprint": "Bubble via Buildprint",
    }
    for name, rest in headings:
        assert market[name] in rest, name
    for block in re.split(r"(?m)^\*\*Preset: ", text)[1:]:
        name = block.split("`")[1]
        has_protection = "branches/" in block and "/protection" in block and "enforce_admins" in block
        assert has_protection == (name in ("single-branch-pr", "dual-branch-pr")), name
